-- No schema change: duplicate enforcement uses an advisory lock + transactional
-- check-then-insert in InsertFeedback (internal/api/handlers/feedback.go).
-- The 1-hour dedup window is applied at the application layer via
-- pg_advisory_xact_lock keyed on (session_id, model_slug, use_case).
