-- No schema change: duplicate enforcement is handled atomically in the INSERT
-- using a WHERE NOT EXISTS subquery scoped to the 1-hour policy window.
-- See: internal/api/handlers/feedback.go InsertFeedback().
