// Package api provides shared HTTP response helpers for the LLM pricing REST API.
// It implements RFC 7807 Problem Details for HTTP APIs, a standard JSON envelope
// for structured responses, and trust metadata computation.
package api

import (
	"encoding/json"

	"github.com/gofiber/fiber/v2"
)

// problemTypeBase is the URI prefix used in all problem type URIs.
// Using an absolute URI makes types globally unambiguous and dereferenceable.
const problemTypeBase = "https://llmrates.live/problems/"

// ProblemDetail represents an RFC 7807 Problem Details object.
// It can be extended with arbitrary key/value pairs via Extensions.
// The Content-Type for responses containing this struct is application/problem+json.
type ProblemDetail struct {
	// Type is a URI reference that identifies the problem type.
	Type string `json:"type"`
	// Title is a short, human-readable summary of the problem type.
	Title string `json:"title"`
	// Status is the HTTP status code generated by the origin server for this occurrence.
	Status int `json:"status"`
	// Detail is a human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail,omitempty"`
	// Instance is a URI reference that identifies the specific occurrence of the problem.
	Instance string `json:"instance,omitempty"`
	// Extensions holds optional problem-specific extension members.
	Extensions map[string]any `json:"extensions,omitempty"`
}

// ErrorHandler is a Fiber-compatible error handler that serialises all errors
// as RFC 7807 Problem Details with Content-Type: application/problem+json.
// Register it as fiber.Config{ErrorHandler: api.ErrorHandler}.
func ErrorHandler(c *fiber.Ctx, err error) error {
	var problem *ProblemDetail

	// If the error is already a ProblemDetail, use it directly.
	if pd, ok := err.(*ProblemDetail); ok {
		problem = pd
	} else if fe, ok := err.(*fiber.Error); ok {
		// Convert a native Fiber error to the appropriate ProblemDetail.
		switch fe.Code {
		case fiber.StatusUnauthorized:
			problem = NewUnauthorized(fe.Message)
		case fiber.StatusForbidden:
			problem = NewForbidden(fe.Message)
		case fiber.StatusNotFound:
			problem = NewNotFound(fe.Message)
		case fiber.StatusTooManyRequests:
			problem = NewTooManyRequests(fe.Message)
		case fiber.StatusBadRequest:
			problem = NewBadRequest(fe.Message)
		default:
			problem = NewInternalError("an unexpected error occurred")
		}
	} else {
		// Unknown error type — treat as internal server error.
		problem = NewInternalError("an unexpected error occurred")
	}

	// Set instance to the request path for traceability.
	if problem.Instance == "" {
		problem.Instance = c.Path()
	}

	body, err := json.Marshal(problem)
	if err != nil {
		// Fallback: plain text to avoid infinite recursion.
		c.Set(fiber.HeaderContentType, fiber.MIMETextPlain)
		return c.Status(fiber.StatusInternalServerError).SendString("internal server error")
	}
	c.Set(fiber.HeaderContentType, "application/problem+json")
	return c.Status(problem.Status).Send(body)
}

// Error implements the error interface, allowing ProblemDetail to be returned
// from Fiber handlers directly.
func (p *ProblemDetail) Error() string {
	return p.Detail
}

// NewUnauthorized returns a 401 Unauthorized ProblemDetail.
func NewUnauthorized(detail string) *ProblemDetail {
	return &ProblemDetail{
		Type:   problemTypeBase + "unauthorized",
		Title:  "Unauthorized",
		Status: fiber.StatusUnauthorized,
		Detail: detail,
	}
}

// NewForbidden returns a 403 Forbidden ProblemDetail.
func NewForbidden(detail string) *ProblemDetail {
	return &ProblemDetail{
		Type:   problemTypeBase + "forbidden",
		Title:  "Forbidden",
		Status: fiber.StatusForbidden,
		Detail: detail,
	}
}

// NewNotFound returns a 404 Not Found ProblemDetail.
func NewNotFound(detail string) *ProblemDetail {
	return &ProblemDetail{
		Type:   problemTypeBase + "not-found",
		Title:  "Not Found",
		Status: fiber.StatusNotFound,
		Detail: detail,
	}
}

// NewBadRequest returns a 400 Bad Request ProblemDetail.
func NewBadRequest(detail string) *ProblemDetail {
	return &ProblemDetail{
		Type:   problemTypeBase + "bad-request",
		Title:  "Bad Request",
		Status: fiber.StatusBadRequest,
		Detail: detail,
	}
}

// NewTooManyRequests returns a 429 Too Many Requests ProblemDetail.
func NewTooManyRequests(detail string) *ProblemDetail {
	return &ProblemDetail{
		Type:   problemTypeBase + "too-many-requests",
		Title:  "Too Many Requests",
		Status: fiber.StatusTooManyRequests,
		Detail: detail,
	}
}

// NewConflict returns a 409 Conflict ProblemDetail.
func NewConflict(detail string) *ProblemDetail {
	return &ProblemDetail{
		Type:   problemTypeBase + "conflict",
		Title:  "Conflict",
		Status: fiber.StatusConflict,
		Detail: detail,
	}
}

// NewGone returns a 410 Gone ProblemDetail.
func NewGone(detail string) *ProblemDetail {
	return &ProblemDetail{
		Type:   problemTypeBase + "gone",
		Title:  "Gone",
		Status: fiber.StatusGone,
		Detail: detail,
	}
}

// NewInternalError returns a 500 Internal Server Error ProblemDetail.
// The detail message is intentionally generic to avoid leaking implementation details.
func NewInternalError(detail string) *ProblemDetail {
	return &ProblemDetail{
		Type:   problemTypeBase + "internal-server-error",
		Title:  "Internal Server Error",
		Status: fiber.StatusInternalServerError,
		Detail: detail,
	}
}
