import { Suspense } from "react"
import type { Metadata } from "next"
import Link from "next/link"

export const dynamic = "force-dynamic"
import { getModels } from "@/lib/api"
import { safeJsonLd } from "@/lib/utils"
import CalculatorClient from "@/components/calculator/CalculatorClient"

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://llmrates.live"

export const metadata: Metadata = {
  title: "LLM Price Calculator | Compare AI Model Costs",
  description:
    "Use our free LLM price calculator to estimate daily, monthly, and yearly API costs. Compare input and output token pricing across leading AI models instantly.",
  keywords: [
    "LLM price calculator",
    "LLM pricing calculator",
    "LLM cost calculator",
    "AI API cost calculator",
    "token cost calculator",
    "AI model pricing calculator",
    "LLM API pricing calculator",
    "AI token cost calculator",
    "AI model cost calculator",
    "token price calculator",
    "LLM cost estimator",
  ],
  alternates: { canonical: "/calculator" },
  openGraph: {
    title: "LLM Price Calculator | Compare AI Model Costs",
    description:
      "Estimate your LLM API spend and compare input and output token costs across leading AI models.",
    url: "/calculator",
    type: "website",
    images: [
      {
        url: `${SITE_URL}/og-image.png`,
        width: 1188,
        height: 613,
        alt: "LLMRates LLM Price Calculator",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "LLM Price Calculator | Compare AI Model Costs",
    description:
      "Estimate daily, monthly, and yearly LLM API costs using current token pricing.",
    images: [`${SITE_URL}/og-image.png`],
  },
}

const FAQs = [
  {
    question: "What is an LLM price calculator?",
    answer:
      "An LLM price calculator estimates what you will pay to use large language model APIs. It combines your input and output token volumes with each model's current per-million-token rates so you can compare projected costs before choosing a provider or model.",
  },
  {
    question: "Is this also an AI token cost calculator?",
    answer:
      "Yes. LLM price calculator, LLM pricing calculator, AI token cost calculator, and AI API cost estimator are common names for tools that apply token usage to provider rates. LLMRates also compares multiple models and projects the same workload by day, month, or year.",
  },
  {
    question: "How do I calculate LLM API costs?",
    answer:
      "Divide your daily input tokens by one million and multiply by the model's input price, then do the same for output tokens and add both amounts. For a monthly estimate, multiply the daily total by 30; for a yearly estimate, multiply it by 365.",
  },
  {
    question: "Are input and output tokens priced differently?",
    answer:
      "Usually, yes. Most LLM providers publish separate rates for tokens sent to the model and tokens generated by the model. Output tokens commonly cost more, so this calculator keeps the two volumes separate and shows both parts of every estimate.",
  },
  {
    question: "Can I compare more than one AI model?",
    answer:
      "Yes. Select up to three models to compare their projected cost for the same workload. The calculator marks the least expensive result while preserving the input and output cost breakdown for every selected model.",
  },
  {
    question: "How current are the LLM prices?",
    answer:
      "LLMRates regularly ingests and reconciles pricing records from multiple sources. Each model includes source and confirmation metadata so you can verify when its price was last checked. Because providers can introduce special tiers, review those details before making a final purchasing decision.",
  },
] as const

const calculatorJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "LLMRates LLM Price Calculator",
  alternateName: "LLM Cost Calculator",
  url: `${SITE_URL}/calculator`,
  description:
    "Free LLM price calculator for estimating and comparing AI API input and output token costs by day, month, or year.",
  applicationCategory: "DeveloperApplication",
  operatingSystem: "Any",
  browserRequirements: "Requires JavaScript",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
  provider: {
    "@type": "Organization",
    name: "LLMRates",
    url: SITE_URL,
  },
  featureList: [
    "Compare up to three LLMs",
    "Separate input and output token costs",
    "Daily, monthly, and yearly estimates",
    "Multi-source reconciled model pricing",
  ],
}

const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    {
      "@type": "ListItem",
      position: 1,
      name: "LLMRates",
      item: SITE_URL,
    },
    {
      "@type": "ListItem",
      position: 2,
      name: "LLM Price Calculator",
      item: `${SITE_URL}/calculator`,
    },
  ],
}

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: FAQs.map(({ question, answer }) => ({
    "@type": "Question",
    name: question,
    acceptedAnswer: {
      "@type": "Answer",
      text: answer,
    },
  })),
}

export default async function CalculatorPage() {
  const allModels = await getModels().catch(() => [])

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: safeJsonLd(calculatorJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: safeJsonLd(breadcrumbJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: safeJsonLd(faqJsonLd) }}
      />

      <main
        className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"
        style={{ paddingTop: "32px", paddingBottom: "64px" }}
      >
        <Suspense fallback={null}>
          <CalculatorClient allModels={allModels} />
        </Suspense>

        <article
          className="font-outfit"
          style={{ marginTop: "56px", maxWidth: "72ch", color: "var(--text)" }}
        >
          <section aria-labelledby="about-calculator" style={{ marginBottom: "40px" }}>
            <h2
              id="about-calculator"
              className="text-xl font-bold"
              style={{ color: "var(--ink)", marginBottom: "12px" }}
            >
              What is an LLM price calculator?
            </h2>
            <p className="text-sm leading-relaxed" style={{ color: "var(--muted)" }}>
              An LLM price calculator turns token usage into an estimated API bill. Enter
              the input and output tokens your application uses each day, select up to
              three models, and compare the projected daily, monthly, or yearly cost using
              current per-million-token rates. This makes it easier to evaluate models from
              OpenAI, Anthropic, Google, and other providers against the same workload.
            </p>
          </section>

          <section aria-labelledby="how-to-calculate" style={{ marginBottom: "40px" }}>
            <h2
              id="how-to-calculate"
              className="text-xl font-bold"
              style={{ color: "var(--ink)", marginBottom: "12px" }}
            >
              How to calculate LLM API cost
            </h2>
            <ol
              className="text-sm leading-relaxed"
              style={{ color: "var(--muted)", paddingLeft: "20px", listStyle: "decimal" }}
            >
              <li style={{ marginBottom: "8px" }}>
                Select one to three AI models so every estimate uses the same workload.
              </li>
              <li style={{ marginBottom: "8px" }}>
                Enter the number of input tokens your application sends each day.
              </li>
              <li style={{ marginBottom: "8px" }}>
                Enter the number of output tokens you expect the models to generate each day.
              </li>
              <li>
                Switch between daily, monthly, and yearly totals to compare your projected spend.
              </li>
            </ol>

            <div
              style={{
                marginTop: "20px",
                padding: "16px 18px",
                border: "1px solid var(--border)",
                backgroundColor: "var(--surfaceLo)",
              }}
            >
              <h3 className="text-sm font-semibold" style={{ color: "var(--ink)", marginBottom: "8px" }}>
                LLM cost formula
              </h3>
              <p className="font-orbitron text-xs leading-relaxed" style={{ color: "var(--muted)" }}>
                Daily cost = (input tokens ÷ 1,000,000 × input rate) +
                (output tokens ÷ 1,000,000 × output rate)
              </p>
              <p className="text-xs leading-relaxed" style={{ color: "var(--dim)", marginTop: "8px" }}>
                Monthly estimates use 30 days. Yearly estimates use 365 days. Rates are
                shown in US dollars per one million tokens.
              </p>
            </div>
          </section>

          <section aria-labelledby="calculator-faqs" style={{ marginBottom: "40px" }}>
            <h2
              id="calculator-faqs"
              className="text-xl font-bold"
              style={{ color: "var(--ink)", marginBottom: "16px" }}
            >
              LLM pricing calculator FAQs
            </h2>
            <div style={{ display: "grid", gap: "20px" }}>
              {FAQs.map(({ question, answer }) => (
                <div key={question}>
                  <h3 className="text-sm font-semibold" style={{ color: "var(--ink)", marginBottom: "6px" }}>
                    {question}
                  </h3>
                  <p className="text-sm leading-relaxed" style={{ color: "var(--muted)" }}>
                    {answer}
                  </p>
                </div>
              ))}
            </div>
          </section>

          <aside
            aria-label="Related LLM pricing tools"
            style={{
              paddingTop: "24px",
              borderTop: "1px solid var(--border)",
            }}
          >
            <h2 className="text-base font-semibold" style={{ color: "var(--ink)", marginBottom: "8px" }}>
              Explore current LLM pricing
            </h2>
            <p className="text-sm leading-relaxed" style={{ color: "var(--muted)" }}>
              Browse the complete{" "}
              <Link
                href="/models"
                className="underline underline-offset-2"
                style={{ color: "var(--accent)" }}
              >
                AI model pricing database
              </Link>
              {" "}or use the{" "}
              <Link
                href="/compare"
                className="underline underline-offset-2"
                style={{ color: "var(--accent)" }}
              >
                LLM comparison tool
              </Link>
              {" "}to evaluate token rates, context windows, and capabilities side by side.
            </p>
          </aside>
        </article>
      </main>
    </>
  )
}
